### ISSUE TITLE
Provide Automatic-Module-Name attribute in MANIFEST.MF

### ISSUE THREAD

**Issue by apssouza22** [sparkapi/SparkJava#11]
At the moment we can not use this library in-app that uses the Java module system.

It would be nice to have an Automatic-Module-Name attribute in MANIFEST.MF. This is very easy to add:
```
<plugin>
    <groupId>org.apache.maven.plugins</groupId>
    <artifactId>maven-jar-plugin</artifactId>
    <version>3.0.2</version>
    <configuration>
        <archive>
            <manifestEntries>
                <Automatic-Module-Name>com.sparkplatform.api</Automatic-Module-Name>
            </manifestEntries>
        </archive>
    </configuration>
</plugin>
```

**Comment by wlmcewen** [comment]
Thanks for the input, Alexsandro. We'll keep this open to address. However, I would like to point out this is a very old and largely unused client for the services at http://sparkplatform.com/. Based on a quick glance at your history, it seems perhaps you're looking for clients for https://spark.apache.org/third-party-projects.html? I'm not familiar enough with that project, but can assure you that the SparkJava client here is unrelated.

**Comment by apssouza22** [comment]
Sorry, wrong repo. I meant this one 😅  https://github.com/perwendel/spark
